### ISSUE TITLE
Add CSV format

### ISSUE THREAD

**Issue by MiguelSavignano** [lightness/github-repo-tools#11]
Hi, nice package

It would be possible to add other output formats like CSV, or tables in markdown, I would like to store this information in those formats.

**Comment by lightness** [comment]
Oops. I didn't noticed that issue :) Sorry

**Comment by lightness** [comment]
Done.
So now you can:
1. Update your package:
```bash
npm i -g github-repo-tools@2.5.1
```
2. Get your data in CSV format:
```bash
grt -u lightness -p koa --csv
```
3. Get your data in Markdown table:
```bash
grt -u lightness -p koa --md
```

Have fun ;)
